// Arter som föreslås när man skriver djurslag.
// Lägg gärna till fler – skriv bara ett nytt namn inom citattecken, följt av komma.
// Man kan också skriva en art som inte finns i listan.
window.SPECIES = [
  // Däggdjur
  'Rådjur',
  'Älg',
  'Kronhjort',
  'Dovhjort',
  'Vildsvin',
  'Räv',
  'Grävling',
  'Fälthare',
  'Skogshare',
  'Kanin',
  'Mård',
  'Mink',
  'Iller',
  'Hermelin',
  'Lodjur',
  'Varg',
  'Björn',
  'Utter',
  'Bäver',
  'Ekorre',
  'Igelkott',
  'Mullvad',
  'Sork',
  'Råtta',
  'Fladdermus',
  'Katt',
  'Hund',
  'Okänt däggdjur',

  // Fåglar
  'Kanadagås',
  'Grågås',
  'Vitkindad gås',
  'Sädgås',
  'Bläsgås',
  'Knölsvan',
  'Sångsvan',
  'Gräsand',
  'Knipa',
  'Storskrake',
  'Skrattmås',
  'Fiskmås',
  'Gråtrut',
  'Silltrut',
  'Havstrut',
  'Tofsvipa',
  'Storspov',
  'Ljungpipare',
  'Strandskata',
  'Enkelbeckasin',
  'Trana',
  'Gråhäger',
  'Storskarv',
  'Kråka',
  'Råka',
  'Kaja',
  'Korp',
  'Skata',
  'Nötskrika',
  'Ringduva',
  'Stadsduva',
  'Stare',
  'Sånglärka',
  'Björktrast',
  'Koltrast',
  'Sädesärla',
  'Ladusvala',
  'Hussvala',
  'Tornseglare',
  'Gulsparv',
  'Gråsparv',
  'Pilfink',
  'Bofink',
  'Grönfink',
  'Ormvråk',
  'Fjällvråk',
  'Tornfalk',
  'Stenfalk',
  'Pilgrimsfalk',
  'Sparvhök',
  'Duvhök',
  'Brun kärrhök',
  'Blå kärrhök',
  'Röd glada',
  'Havsörn',
  'Kungsörn',
  'Fiskgjuse',
  'Berguv',
  'Hornuggla',
  'Jorduggla',
  'Kattuggla',
  'Fasan',
  'Rapphöna',
  'Orre',
  'Tjäder',
  'Okänd fågel',
  'Fågelflock (okänd art)',
];
