// =============================================================
// Arter och djurgrupper
// =============================================================
// Varje art hör till en grupp. Gruppen bestämmer vilken ikon som visas på kartan.
// Lägg till en art: skriv en ny rad ['Namn', 'grupp'], följt av komma.
// Arter som användarna själva skriver in sparas i databasen (tabellen custom_species).

// kind = 'daggdjur', 'fagel' eller 'annat' (används av filtret "Alla däggdjur/fåglar").
// icon = ikonen som visas. fallback = används om telefonen är för gammal för ikonen.
window.SPECIES_GROUPS = {
  // Däggdjur
  alg:        { kind: 'daggdjur', label: 'Älg',                                  icon: '🫎', fallback: '🦌' },
  hjort:      { kind: 'daggdjur', label: 'Hjortdjur (rådjur, kronhjort …)',      icon: '🦌' },
  vildsvin:   { kind: 'daggdjur', label: 'Vildsvin',                             icon: '🐗' },
  bjorn:      { kind: 'daggdjur', label: 'Björn',                                icon: '🐻' },
  varg:       { kind: 'daggdjur', label: 'Varg',                                 icon: '🐺' },
  lodjur:     { kind: 'daggdjur', label: 'Lodjur',                               icon: '🐆' },
  rav:        { kind: 'daggdjur', label: 'Räv och mårdhund',                     icon: '🦊' },
  hare:       { kind: 'daggdjur', label: 'Hare och kanin',                       icon: '🐇' },
  mard:       { kind: 'daggdjur', label: 'Mårddjur (grävling, mård, mink …)',    icon: '🦡' },
  vattendjur: { kind: 'daggdjur', label: 'Bäver och utter',                      icon: '🦫' },
  sal:        { kind: 'daggdjur', label: 'Säl',                                  icon: '🦭' },
  ekorre:     { kind: 'daggdjur', label: 'Ekorre',                               icon: '🐿️' },
  igelkott:   { kind: 'daggdjur', label: 'Igelkott',                             icon: '🦔' },
  smadjur:    { kind: 'daggdjur', label: 'Smådjur (möss, sorkar, näbbmöss …)',   icon: '🐭' },
  fladdermus: { kind: 'daggdjur', label: 'Fladdermöss',                          icon: '🦇' },
  hund:       { kind: 'daggdjur', label: 'Hund',                                 icon: '🐕' },
  katt:       { kind: 'daggdjur', label: 'Katt',                                 icon: '🐈' },
  daggdjur:   { kind: 'daggdjur', label: 'Övrigt däggdjur',                      icon: '🐾' },

  // Fåglar
  gas:        { kind: 'fagel', label: 'Gäss',                                 icon: '🪿', fallback: '🦆' },
  svan:       { kind: 'fagel', label: 'Svanar',                               icon: '🦢' },
  and:        { kind: 'fagel', label: 'Änder och andra sjöfåglar',            icon: '🦆' },
  vitfagel:   { kind: 'fagel', label: 'Vitfåglar (måsar, trutar, tärnor)',    icon: '🕊️' },
  storfagel:  { kind: 'fagel', label: 'Stora fåglar (trana, häger, skarv)',   icon: '🦩' },
  rovfagel:   { kind: 'fagel', label: 'Rovfåglar',                            icon: '🦅' },
  uggla:      { kind: 'fagel', label: 'Ugglor',                               icon: '🦉' },
  krakfagel:  { kind: 'fagel', label: 'Kråkfåglar',                           icon: '🐦‍⬛', fallback: '🐦' },
  honsfagel:  { kind: 'fagel', label: 'Hönsfåglar (fasan, orre, tjäder …)',   icon: '🐓' },
  mellanfagel:{ kind: 'fagel', label: 'Duvor, vadare och hackspettar',        icon: '🐦' },
  smafagel:   { kind: 'fagel', label: 'Småfåglar',                            icon: '🐤' },
  fagel:      { kind: 'fagel', label: 'Övrig fågel',                          icon: '🐦' },

  ovrigt:     { kind: 'annat', label: 'Annat',                                icon: '❓' },
};

window.SPECIES = [
  // ---------- Däggdjur ----------
  ['Älg', 'alg'],
  ['Rådjur', 'hjort'],
  ['Kronhjort', 'hjort'],
  ['Dovhjort', 'hjort'],
  ['Ren', 'hjort'],
  ['Vildsvin', 'vildsvin'],
  ['Björn', 'bjorn'],
  ['Varg', 'varg'],
  ['Lodjur', 'lodjur'],
  ['Räv', 'rav'],
  ['Fjällräv', 'rav'],
  ['Mårdhund', 'rav'],
  ['Fälthare', 'hare'],
  ['Skogshare', 'hare'],
  ['Kanin', 'hare'],
  ['Grävling', 'mard'],
  ['Mård', 'mard'],
  ['Mink', 'mard'],
  ['Iller', 'mard'],
  ['Hermelin', 'mard'],
  ['Småvessla', 'mard'],
  ['Järv', 'mard'],
  ['Tvättbjörn', 'mard'],
  ['Utter', 'vattendjur'],
  ['Bäver', 'vattendjur'],
  ['Bisamråtta', 'vattendjur'],
  ['Gråsäl', 'sal'],
  ['Knubbsäl', 'sal'],
  ['Vikaresäl', 'sal'],
  ['Ekorre', 'ekorre'],
  ['Flygekorre', 'ekorre'],
  ['Igelkott', 'igelkott'],
  ['Mullvad', 'smadjur'],
  ['Vanlig näbbmus', 'smadjur'],
  ['Dvärgnäbbmus', 'smadjur'],
  ['Vattennäbbmus', 'smadjur'],
  ['Skogssork', 'smadjur'],
  ['Åkersork', 'smadjur'],
  ['Vattensork', 'smadjur'],
  ['Sork (okänd art)', 'smadjur'],
  ['Större skogsmus', 'smadjur'],
  ['Mindre skogsmus', 'smadjur'],
  ['Husmus', 'smadjur'],
  ['Brunråtta', 'smadjur'],
  ['Hasselmus', 'smadjur'],
  ['Fjällämmel', 'smadjur'],
  ['Nordfladdermus', 'fladdermus'],
  ['Dvärgfladdermus', 'fladdermus'],
  ['Vattenfladdermus', 'fladdermus'],
  ['Långörad fladdermus', 'fladdermus'],
  ['Gråskimlig fladdermus', 'fladdermus'],
  ['Stor fladdermus', 'fladdermus'],
  ['Fransfladdermus', 'fladdermus'],
  ['Mustaschfladdermus', 'fladdermus'],
  ['Fladdermus (okänd art)', 'fladdermus'],
  ['Hund', 'hund'],
  ['Katt', 'katt'],
  ['Okänt däggdjur', 'daggdjur'],

  // ---------- Gäss och svanar ----------
  ['Kanadagås', 'gas'],
  ['Grågås', 'gas'],
  ['Vitkindad gås', 'gas'],
  ['Sädgås', 'gas'],
  ['Tundrasädgås', 'gas'],
  ['Bläsgås', 'gas'],
  ['Fjällgås', 'gas'],
  ['Prutgås', 'gas'],
  ['Gås (okänd art)', 'gas'],
  ['Knölsvan', 'svan'],
  ['Sångsvan', 'svan'],
  ['Mindre sångsvan', 'svan'],

  // ---------- Änder och andra sjöfåglar ----------
  ['Gräsand', 'and'],
  ['Kricka', 'and'],
  ['Bläsand', 'and'],
  ['Stjärtand', 'and'],
  ['Snatterand', 'and'],
  ['Skedand', 'and'],
  ['Årta', 'and'],
  ['Brunand', 'and'],
  ['Vigg', 'and'],
  ['Bergand', 'and'],
  ['Knipa', 'and'],
  ['Alfågel', 'and'],
  ['Sjöorre', 'and'],
  ['Svärta', 'and'],
  ['Ejder', 'and'],
  ['Storskrake', 'and'],
  ['Småskrake', 'and'],
  ['Salskrake', 'and'],
  ['Gravand', 'and'],
  ['Storlom', 'and'],
  ['Smålom', 'and'],
  ['Skäggdopping', 'and'],
  ['Gråhakedopping', 'and'],
  ['Svarthakedopping', 'and'],
  ['Smådopping', 'and'],
  ['Sothöna', 'and'],
  ['Rörhöna', 'and'],
  ['And (okänd art)', 'and'],

  // ---------- Vitfåglar ----------
  ['Skrattmås', 'vitfagel'],
  ['Fiskmås', 'vitfagel'],
  ['Gråtrut', 'vitfagel'],
  ['Silltrut', 'vitfagel'],
  ['Havstrut', 'vitfagel'],
  ['Dvärgmås', 'vitfagel'],
  ['Tretåig mås', 'vitfagel'],
  ['Fisktärna', 'vitfagel'],
  ['Silvertärna', 'vitfagel'],
  ['Kentsk tärna', 'vitfagel'],
  ['Skräntärna', 'vitfagel'],
  ['Småtärna', 'vitfagel'],
  ['Mås/trut (okänd art)', 'vitfagel'],

  // ---------- Stora fåglar ----------
  ['Trana', 'storfagel'],
  ['Gråhäger', 'storfagel'],
  ['Ägretthäger', 'storfagel'],
  ['Rördrom', 'storfagel'],
  ['Vit stork', 'storfagel'],
  ['Storskarv', 'storfagel'],

  // ---------- Rovfåglar ----------
  ['Ormvråk', 'rovfagel'],
  ['Fjällvråk', 'rovfagel'],
  ['Bivråk', 'rovfagel'],
  ['Tornfalk', 'rovfagel'],
  ['Stenfalk', 'rovfagel'],
  ['Lärkfalk', 'rovfagel'],
  ['Pilgrimsfalk', 'rovfagel'],
  ['Jaktfalk', 'rovfagel'],
  ['Sparvhök', 'rovfagel'],
  ['Duvhök', 'rovfagel'],
  ['Brun kärrhök', 'rovfagel'],
  ['Blå kärrhök', 'rovfagel'],
  ['Ängshök', 'rovfagel'],
  ['Röd glada', 'rovfagel'],
  ['Brun glada', 'rovfagel'],
  ['Havsörn', 'rovfagel'],
  ['Kungsörn', 'rovfagel'],
  ['Fiskgjuse', 'rovfagel'],
  ['Rovfågel (okänd art)', 'rovfagel'],

  // ---------- Ugglor ----------
  ['Berguv', 'uggla'],
  ['Hornuggla', 'uggla'],
  ['Jorduggla', 'uggla'],
  ['Kattuggla', 'uggla'],
  ['Slaguggla', 'uggla'],
  ['Lappuggla', 'uggla'],
  ['Pärluggla', 'uggla'],
  ['Sparvuggla', 'uggla'],
  ['Hökuggla', 'uggla'],
  ['Fjälluggla', 'uggla'],
  ['Uggla (okänd art)', 'uggla'],

  // ---------- Kråkfåglar ----------
  ['Kråka', 'krakfagel'],
  ['Råka', 'krakfagel'],
  ['Kaja', 'krakfagel'],
  ['Korp', 'krakfagel'],
  ['Skata', 'krakfagel'],
  ['Nötskrika', 'krakfagel'],
  ['Lavskrika', 'krakfagel'],
  ['Nötkråka', 'krakfagel'],

  // ---------- Hönsfåglar ----------
  ['Fasan', 'honsfagel'],
  ['Rapphöna', 'honsfagel'],
  ['Vaktel', 'honsfagel'],
  ['Orre', 'honsfagel'],
  ['Tjäder', 'honsfagel'],
  ['Järpe', 'honsfagel'],
  ['Dalripa', 'honsfagel'],
  ['Fjällripa', 'honsfagel'],

  // ---------- Duvor, vadare, hackspettar m.fl. ----------
  ['Ringduva', 'mellanfagel'],
  ['Stadsduva', 'mellanfagel'],
  ['Skogsduva', 'mellanfagel'],
  ['Turkduva', 'mellanfagel'],
  ['Turturduva', 'mellanfagel'],
  ['Tofsvipa', 'mellanfagel'],
  ['Storspov', 'mellanfagel'],
  ['Småspov', 'mellanfagel'],
  ['Ljungpipare', 'mellanfagel'],
  ['Större strandpipare', 'mellanfagel'],
  ['Mindre strandpipare', 'mellanfagel'],
  ['Fjällpipare', 'mellanfagel'],
  ['Kustpipare', 'mellanfagel'],
  ['Strandskata', 'mellanfagel'],
  ['Enkelbeckasin', 'mellanfagel'],
  ['Dubbelbeckasin', 'mellanfagel'],
  ['Dvärgbeckasin', 'mellanfagel'],
  ['Morkulla', 'mellanfagel'],
  ['Rödbena', 'mellanfagel'],
  ['Gluttsnäppa', 'mellanfagel'],
  ['Skogssnäppa', 'mellanfagel'],
  ['Grönbena', 'mellanfagel'],
  ['Drillsnäppa', 'mellanfagel'],
  ['Brushane', 'mellanfagel'],
  ['Kärrsnäppa', 'mellanfagel'],
  ['Kustsnäppa', 'mellanfagel'],
  ['Myrspov', 'mellanfagel'],
  ['Rödspov', 'mellanfagel'],
  ['Vadare (okänd art)', 'mellanfagel'],
  ['Större hackspett', 'mellanfagel'],
  ['Mindre hackspett', 'mellanfagel'],
  ['Gröngöling', 'mellanfagel'],
  ['Gråspett', 'mellanfagel'],
  ['Spillkråka', 'mellanfagel'],
  ['Tretåig hackspett', 'mellanfagel'],
  ['Vitryggig hackspett', 'mellanfagel'],
  ['Göktyta', 'mellanfagel'],
  ['Gök', 'mellanfagel'],
  ['Nattskärra', 'mellanfagel'],
  ['Kungsfiskare', 'mellanfagel'],
  ['Härfågel', 'mellanfagel'],
  ['Kornknarr', 'mellanfagel'],
  ['Vattenrall', 'mellanfagel'],
  ['Småfläckig sumphöna', 'mellanfagel'],

  // ---------- Småfåglar ----------
  ['Stare', 'smafagel'],
  ['Sånglärka', 'smafagel'],
  ['Trädlärka', 'smafagel'],
  ['Tofslärka', 'smafagel'],
  ['Björktrast', 'smafagel'],
  ['Koltrast', 'smafagel'],
  ['Taltrast', 'smafagel'],
  ['Rödvingetrast', 'smafagel'],
  ['Dubbeltrast', 'smafagel'],
  ['Ringtrast', 'smafagel'],
  ['Sädesärla', 'smafagel'],
  ['Gulärla', 'smafagel'],
  ['Forsärla', 'smafagel'],
  ['Ängspiplärka', 'smafagel'],
  ['Trädpiplärka', 'smafagel'],
  ['Skärpiplärka', 'smafagel'],
  ['Ladusvala', 'smafagel'],
  ['Hussvala', 'smafagel'],
  ['Backsvala', 'smafagel'],
  ['Tornseglare', 'smafagel'],
  ['Gulsparv', 'smafagel'],
  ['Sävsparv', 'smafagel'],
  ['Ortolansparv', 'smafagel'],
  ['Snösparv', 'smafagel'],
  ['Lappsparv', 'smafagel'],
  ['Gråsparv', 'smafagel'],
  ['Pilfink', 'smafagel'],
  ['Bofink', 'smafagel'],
  ['Bergfink', 'smafagel'],
  ['Grönfink', 'smafagel'],
  ['Steglits', 'smafagel'],
  ['Grönsiska', 'smafagel'],
  ['Gråsiska', 'smafagel'],
  ['Hämpling', 'smafagel'],
  ['Vinterhämpling', 'smafagel'],
  ['Domherre', 'smafagel'],
  ['Stenknäck', 'smafagel'],
  ['Mindre korsnäbb', 'smafagel'],
  ['Större korsnäbb', 'smafagel'],
  ['Tallbit', 'smafagel'],
  ['Rosenfink', 'smafagel'],
  ['Talgoxe', 'smafagel'],
  ['Blåmes', 'smafagel'],
  ['Svartmes', 'smafagel'],
  ['Tofsmes', 'smafagel'],
  ['Entita', 'smafagel'],
  ['Talltita', 'smafagel'],
  ['Stjärtmes', 'smafagel'],
  ['Nötväcka', 'smafagel'],
  ['Trädkrypare', 'smafagel'],
  ['Gärdsmyg', 'smafagel'],
  ['Järnsparv', 'smafagel'],
  ['Rödhake', 'smafagel'],
  ['Näktergal', 'smafagel'],
  ['Blåhake', 'smafagel'],
  ['Rödstjärt', 'smafagel'],
  ['Svart rödstjärt', 'smafagel'],
  ['Buskskvätta', 'smafagel'],
  ['Stenskvätta', 'smafagel'],
  ['Grå flugsnappare', 'smafagel'],
  ['Svartvit flugsnappare', 'smafagel'],
  ['Kungsfågel', 'smafagel'],
  ['Gransångare', 'smafagel'],
  ['Lövsångare', 'smafagel'],
  ['Grönsångare', 'smafagel'],
  ['Svarthätta', 'smafagel'],
  ['Trädgårdssångare', 'smafagel'],
  ['Törnsångare', 'smafagel'],
  ['Ärtsångare', 'smafagel'],
  ['Sävsångare', 'smafagel'],
  ['Rörsångare', 'smafagel'],
  ['Kärrsångare', 'smafagel'],
  ['Härmsångare', 'smafagel'],
  ['Gräshoppsångare', 'smafagel'],
  ['Törnskata', 'smafagel'],
  ['Varfågel', 'smafagel'],
  ['Sidensvans', 'smafagel'],
  ['Strömstare', 'smafagel'],
  ['Småfågel (okänd art)', 'smafagel'],

  // ---------- Övrigt ----------
  ['Okänd fågel', 'fagel'],
  ['Fågelflock (okänd art)', 'fagel'],
];
